# Config entities.
attribution.attribution_license.*:
  type: config_entity
  label: License
  mapping:
    id:
      type: string
      label: ID
    identifier:
      type: string
      label: Identifier
    name:
      type: label
      label: Name
    osiCertified:
      type: bool
      label: OSI certified
    deprecated:
      type: bool
      label: Deprecated
    link:
      type: string
      label: Link
# Block instance.
block.settings.attribution:
  type: block_settings
  label: 'Attribution'
  mapping:
    license:
      type: string
      label: License
    disclaimer:
      type: string
      label: Disclaimer
# Field instance.
field.field_settings.attribution:
  type: mapping
  label: Attribution field settings
  mapping:
    default:
      type: string
      label: Default license
    licenses:
      type: sequence
      label: Licenses
      sequence:
        type: string
# Default value.
field.value.attribution:
  type: mapping
  label: Default value
  mapping:
    source_name:
      type: string
      label: Source name
    source_link:
      type: uri
      label: Source link
    author_name:
      type: string
      label: Author name
    author_link:
      type: uri
      label: Author link
    license:
      type: string
      label: License
